{
  "ListeningAddr": "localhost:3456",
  "ServerAddr": "localhost:5001", # Замените 5001 на порт вашего сервера
  "ClientCommand": "user()", # Замените на команду, с помощью которой запускается ваш клиент
  "WaitForClients": false
}