{
  "ListeningAddr": "localhost:3456",
  "ServerAddr": "localhost:5001", # Замените 5001 на порт вашего сервера
  "ClientCommand": "C:/Users/lokod/AppData/Local/Programs/Python/Python38-32/python.exe client2.py", # Замените на команду, с помощью которой запускается ваш клиент
  "WaitForClients": false
}